### PR TITLE
Development branch

### PR DESCRIPTION
**Pull request by Tom-Nagy**
Hi there,
I hope i am not messing this up here.
I have added code structure for Blueprint (quite easy to use) and created a table rendering the list of companies.
issue fixed:
#22 
#17

### CODE REVIEW

**Review by auxfuse — CHANGES_REQUESTED** [review]
Hi @Tom-Nagy great PR. Lots going on in this, and a lot that will need to be aligned with the stuff that's already been merged.

The only issue right now is that we have some merge conflicts in the app.py. Can you take a look and resolve those conflicts as you see fit to make it fit your Blueprints? Thank you for your excellent work on this. 🤜

**Comment by Tom-Nagy** [comment]
I have done some change in the structure of the code to allow the changes.
Can you have a look please.
You will probably need to request a change from my part for resolving conflicts but the changes should bring better base solutions.

**Review by Tom-Nagy — COMMENTED** [review]
I have reviewed the files and found no conflicts.

**Comment by Tom-Nagy** [comment]
I have reviewed the files and found no conflicts with the changes i made on my last commit.

**Review by stefdworschak — APPROVED** [review]
@Tom-Nagy I agree with @auxfuse that there is a lot going on. In future I would like to see Pull Requests like this split up into smaller multiple smaller Pull Request. Also there are a few things structurally that we might want to change, but overall I think it's really good and I am going to approve and merge this now.

**Pull request merged**
